[package]
name = "aes-cbc"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
cbc = "0.1.2"
rand = "0.8.5"
rpassword = "7.3.1"
sha2 = "0.10.8"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
# overflow-checks = false
debug = false
